---
permalink: online-help/concept-what-options-do-i-have-when-i-see-the-fix-it-button.html
sidebar: sidebar
keywords: fix it
summary: 'The Fix It button enables you to fix an issue that Unified Manager has been notified about through an event.'
---
= What options do I have when I see the *Fix It* button
:icons: font
:imagesdir: ../media/

[.lead]
The *Fix It* button enables you to fix an issue that Unified Manager has been notified about through an event.

We recommend that you click the *Fix It* button to fix the issue when it is available. However, if you are not sure that you want to resolve the issue as recommended by Unified Manager, you can perform the following actions:

|===
| What do you want to do?| Action
a|
Have Unified Manager fix the issue.
a|
Click the *Fix It* button.
a|
Do not fix the issue at this time and hide this management action.
a|
Click the down arrow and click *Dismiss*.
a|
Display the details for this event so you can better understand the issue.
a|
Click the down arrow and click *View Event Details* to display the Event details page.
a|
Display the details for this storage object so you can better understand the issue.
a|
Click the name of the storage object to display details in either the Performance Explorer or Health Details page.
|===
Prior to clicking the *Fix It* button you should make a note of the object name (for example, "`cluster fas8040-206`" or "`volume phil_DB`") so that you can check the list of events later to verify that the corresponding event is in the Obsolete state - meaning that the fix was successful.

In some cases the fix is reflected in the next 15 minute configuration poll. In other cases it can take up to 24 hours for the configuration change to be verified and for the event to be obsoleted.
