---
permalink: online-help/concept_configuring_the_destination_and_schedule_for_database_dump_backups.html
sidebar: sidebar
keywords: 
summary: 'You can configure the Unified Manager database backup settings to set the database backup path, retention count, and backup schedules. You can enable daily or weekly scheduled backups. By default, scheduled backups are disabled.'
---
= Configuring database backup settings
:icons: font
:imagesdir: ../media/

[.lead]
You can configure the Unified Manager database backup settings to set the database backup path, retention count, and backup schedules. You can enable daily or weekly scheduled backups. By default, scheduled backups are disabled.

== Before you begin

* You must have the Operator, Application Administrator, or Storage Administrator role.
* You must have a minimum of 150 GB of space available in the location you define as the backup path.
+
It is recommended that you use a remote location that is external to the Unified Manager host system.

* When Unified Manager is installed on a Linux system, verify that the "`jboss`" user has write permissions to the backup directory.
* You should not schedule backup operations to occur immediately after a new cluster has been added while Unified Manager is collecting 15 days of historical performance data.

== About this task

More time is required the first time a backup is performed than for subsequent backups because the first backup is a full backup. A full backup can be over 1 GB and can take three to four hours. Subsequent backups are incremental and require less time.

[NOTE]
====
If you find that the number of incremental backup files is getting too large for the space you have allocated for backups, see https://kb.netapp.com/app/answers/answer_view/a_id/1087704/loc/en_US[Knowledgebase Answer 1087704] to learn how you can create a new full backup periodically to replace the old full backup and all of its' child incremental files.
====

== Steps

. In the left navigation pane, click *General* > *Database Backup*.
. In the *Database Backup* page, click *Backup Settings*.
. Configure the appropriate values for a backup path, retention count, and schedule.
+
The default value for retention count is 10; you can use 0 for creating unlimited backups.

. Select the *Scheduled Daily* or *Scheduled Weekly* button, and then specify the schedule details.
. Click *Apply*.

*Related information*

xref:reference_database_backup_page.adoc[Database Backup page]
