---
permalink: online-help/reference_database_backup_page.html
sidebar: sidebar
keywords: 
summary: 'The Database Backup page displays a list of backups created by Unified Manager and provides information about the backup name, size, creation time, and schedule.'
---
= Database Backup page
:icons: font
:imagesdir: ../media/

[.lead]
The Database Backup page displays a list of backups created by Unified Manager and provides information about the backup name, size, creation time, and schedule.

You must have the Application Administrator or Storage Administrator role.

== Command buttons

* *Actions*
+
Displays the Backup Settings dialog box, which enables you to specify a backup path, retention count, and backup schedule.

== List View

The list view displays, in tabular format, information about the backups created by Unified Manager. You can use the column filters to customize the data that is displayed.

* *Name*
+
Displays the name of the selected backup.

* *Size*
+
Displays the size of the selected backup.

* *Creation Time*
+
Displays the creation date and time of the selected backup.

* *Schedule*
+
Displays the status of the backup operation. Also indicates whether it is a scheduled backup or not.

*Related information*

xref:concept_configuring_the_destination_and_schedule_for_database_dump_backups.adoc[Configuring database backup settings]

xref:concept_backup_and_restore_using_a_mysql_database_dump.adoc[What a database backup is]
