---
permalink: online-help/task-viewing-and-adding-vcenter-servers.html
sidebar: sidebar
keywords: vCenter server
summary: 'For viewing and troubleshooting the performance of the virtual machines \(VMs\), the associated vCenters must be added on your Active IQ Unified Manager instance.'
---
= Viewing and adding vCenter servers
:icons: font
:imagesdir: ../media/

[.lead]
For viewing and troubleshooting the performance of the virtual machines (VMs), the associated vCenters must be added on your Active IQ Unified Manager instance.

== Before you begin

Before adding or viewing the vCenters, ensure the following:

* You are aware of the vCenter names.
* The vCenters are reachable for a successful discovery.
* You know the IP address and have the credentials while adding the vCenter. The credentials must be of a vCenter administrator or a root user with read-only access to vCenter.
* The vCenter that you want to add runs vSphere 6.5 or later.
* The data collection setting in the vCenter server is set to level 3 for 5-minute interval
* The latency values in vCenter are configured in milliseconds, and not in microseconds, for successful calculations of the latency values.
* The time of the vCenter belongs to the time zone of the vCenter.

== About this task

For every vCenter added and discovered, Unified Manager collects the configuration data, such as the vCenter and ESXi server details, ONTAP mapping, datastore details, and number of VMs hosted. It further collects the performance metrics of the components.

== Steps

. Go to *VMWARE* > *vCenter,* and check whether your vCenter is available on the list.
+
[NOTE]
====
If your vCenter is not available, you must add the vCenter.
====

 .. Click *Add*.
 .. Add the correct IP address for the vCenter and ensure that the device is reachable.
 .. Add the user name and password of the administrator or root user with read-only access to vCenter.
 .. Add the custom port number if you are using any port other than the default `443`.
 .. Click *Save*. Upon successful discovery, a server certificate is displayed for you to accept.
+
When you accept the certificate, the vCenter is added to the list of available vCenters. Adding the device does not result into data collection for the associated VMs, and the collection occurs at the scheduled intervals.

. If your vCenter is available on the *vCenters* page, check its status. Hovering your mouse over the *Status* field displays whether your vCenter is performing as expected or whether there is a warning or error.
+
[NOTE]
====
Adding the vCenter allows you to view the following statuses. However, the performance and latency data of the corresponding VMs might take up to an hour after adding the vCenter to be accurately reflected.
====

 ** Green: Normal, indicating that the vCenter has been discovered, and performance metrics have been successfully collected
 ** Yellow: Warning (for example, when the statistics level for the vCenter server has not been set to 3 or above to obtain statistics for each object)
 ** Orange: Error (indicates any internal errors, such as exception, failure in configuration data collection, or the vCenter being unreachable)
You can click the column display icon (*Show/Hide*) to view the status message for a vCenter status and troubleshoot the issue.

. In case the vCenter is unreachable or the credentials have changed, edit the vCenter details. Select the vCenter, and then click *Edit*.
. Make the necessary changes on the *Edit VMware vCenter Server* page.
. Click *Save*.
+
Upon successful discovery, the status of the vCenter changes.
