---
permalink: online-help/task-exporting-storage-data-as-reports.html
sidebar: sidebar
keywords: 
summary: 'You can export data to a comma-separated values \(.csv\) file or \(.pdf\) document, and use the exported data to build reports. For example, if there are 10 critical events that have not been resolved, you can export the data from the Event Management inventory page to create a report, and then take appropriate action.'
---
= Exporting data to CSV and PDF files for reporting
:icons: font
:imagesdir: ../media/

[.lead]
You can export data to a comma-separated values (`.csv`) file or (`.pdf`) document, and use the exported data to build reports. For example, if there are 10 critical events that have not been resolved, you can export the data from the Event Management inventory page to create a report, and then take appropriate action.

== About this task

You can export data to a `.csv` file or `.pdf` document from the Storage, Network, and Quality of Service inventory pages and use the exported data to build reports.

== Steps

. Perform one of the following actions:
+
[cols="1a,1a" options="header"]
|===
| If you want to export...| Do this...
a|
Event details
a|
Click *Event Management* from the left-navigation menu.
a|
Storage object inventory details
a|
Click *Storage* or *Network* from the left-navigation menu, and then select a storage object. Then choose one of the *Health*, *Capacity*, *Performance*, or *Relationship* views.
a|
Storage capacity and protection history details
a|
Click *Storage* > *Aggregates* or *Storage* > *Volumes*, then select a single aggregate or volume.
a|
Storage object top 10 performance details
a|
Click *Storage* > *Clusters* > *Performance/All Clusters*, then select a cluster and choose the *Top Performers* tab. Then select a storage object and performance counter.
a|
QoS Policy Group details
a|
Click *Storage* > *QoS Policy Groups* from the left-navigation menu.
|===

. Click the *Export* button.
. Click *CSV file* or *PDF Document* to confirm the export request.
+
From the Top Performers tab you can choose to download a report of the statistics for the single cluster you are viewing or for all clusters in the data center.
+
The file is downloaded.

. Open the `.csv` file or `.pdf` document in the appropriate application.

*Related information*

xref:reference-health-all-clusters-view.adoc[Health: All Clusters view]

xref:task-scheduling-a-report.adoc[Scheduling a report]
