---
settings:
  name: Active IQ Unified Manager 9.7
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
  versions:
    - name: Unified Manager
      url: /active-iq-unified-manager-97
      version-number: "9.7"
    - name: Unified Manager
      url: /active-iq-unified-manager-99
      version-number: "9.9"
    - name: Unified Manager
      url: /active-iq-unified-manager-98
      version-number: "9.8"
    - name: Unified Manager
      url: /oncommand-unified-manager-95
      version-number: "9.5"
sidebar:
  entries:
    - title: Home
      url: "/index.html"
    - title: Release notes
      url: "/release-notes.html"
    - title: Get started
      entries:
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
        - title: Quick start install for Linux
          url: /install-linux/qsg-linux.html
        - title: Quick start install for Windows
          url: /install-windows/qsg-windows.html
    - section: install-vapp
    - section: install-linux
    - section: install-windows
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - section: data-protection
    - section: reporting
    - section: api-automation
    - title: Legal
      url: "/legal-notices.html"
homepage:
  tiles:
    - title: Get started
      links:
        - title: Product Overview
          url: /storage-mgmt/concept-introduction-to-unified-manager.html
        - title: Release notes
          url: /release-notes.html
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
        - title: Quick start install for Linux
          url: /install-linux/qsg-linux.html
        - title: Quick start install for Windows
          url: /install-windows/qsg-windows.html
    - title: Install & configure Unified Manager
      links:
        - title: Install & upgrade on VMware vSphere systems
          url: /install-vapp/concept-requirements-for-installing-unified-manager.html
        - title: Install & upgrade on Linux systems
          url: /install-linux/concept-requirements-for-installing-unified-manager.html
        - title: Install & upgrade on Windows systems
          url: /install-windows/concept-requirements-for-installing-unified-manager.html
        - title: Configure Unified Manager
          url: /config/concept-configuring-unified-manager.html
        - title: Manage feature settings
          url: /config/concept-manage-feature-settings.html
        - title: Manage role-based access
          url: /config/concept-manage-user-access.html
    - title: Performance monitoring
      links:
        - title: Performance thresholds
          url: /performance-checker/concept-manage-performance-thresholds.html
        - title: Cluster performance
          url: /performance-checker/concept-monitor-cluster-performance-from-dashboard.html
        - title: QoS policy group
          url: /performance-checker/concept-manage-performance-using-qos-policy-group-information.html
        - title: Workload analyzer
          url: /performance-checker/concept-troubleshooting-workloads-using-workload-analyzer.html
        - title: Workload performance
          url: /performance-checker/concept-collect-data-and-monitor-workload-performance.html
        - title: Manage Performance
          url: /performance-checker/concept-manage-performance-using-perf-capacity-available-iops.html
    - title: Storage and object health monitoring
      links:
        - title: Workloads
          url: /storage-mgmt/concept-provision-and-manage-workloads.html
        - title: Virtual infrastructure
          url: /storage-mgmt/concept-monitor-vmware-virtual-infrastructure.html
        - title: MetroCluster configurations
          url: /storage-mgmt/concept-manage-and-monitor-metrocluster-configurations.html
        - title: Clusters and cluster object health
          url: /health-checker/concept-manage-and-monitor-clusters-and-cluster-object-health.html
        - title: Health thresholds
          url: /health-checker/concept-manage-health-thresholds.html
        - title: Send AutoSupport messages and support bundles
          url: /health-checker/task-send-asup-to-technical-support.html
    - title: Data protection monitoring
      links:
        - title: Set up protection relationship
          url: /data-protection/task-set-up-protection-relationships-in-unified-manager.html
        - title: Perform failover and failback
          url: /data-protection/task-perform-protection-relationship-failover-and-failback.html
        - title: Manage protection relationship
          url: /data-protection/concept-manage-and-monitor-protection-relationships.html
        - title: Monitor disaster recovery relationships
          url: /data-protection/task-monitor-storage-vms-using-relationships-page.html
        - title: Generate reports
          url: /reporting/concept-unified-manager-reporting.html
    - title: Use REST APIs
      links:
        - title: Get started
          url: /api-automation/concept-api-url-and-categories.html
        - title: Access Unified Manager APIs
          url: /api-automation/concept-rest-api-access-and-authentication-in-um-apis.html
        - title: Manage storage objects
          url: /api-automation/concept-data-center-apis.html
        - title: Access ONTAP APIs
          url: /api-automation/concept-gateway-apis.html
        - title: Common workflows
          url: /api-automation/concept-workflow-intro.html
        - title: Provision storage
          url: /api-automation/concept-provision-workflow.html
    - title: Events and alerts
      links:
        - title: Dashboard
          url: /storage-mgmt/reference-dashboard-page.html
        - title: Event workflow
          url: /events/concept-what-happens-when-an-event-is-received.html
        - title: Active IQ platform events
          url: /events/concept-how-active-iq-platform-events-are-generated.html
        - title: Events and severity types
          url: /events/reference-list-of-events-and-severity-types.html
        - title: Remediation events
          url: /storage-mgmt/concept-fix-ontap-issues-directly-from-unified-manager.html
        - title: Automatic remediation
          url: /storage-mgmt/reference-what-ontap-issues-can-unified-manager-fix.html
    - title: More resources
      links:
        - title: Unified Manager videos
          url: https://www.youtube.com/playlist?list=PLdXI3bZJEw7mp3jFSg0IJgo3oeDQRY-Gl
        - title: Unified Manager blogs
          url: https://www.netapp.com/blog/#q=active%20iq%20unified%20manager&t=Blogs&sort=%40publish_date_mktg%20descending&layout=card&f:@facet_language_mktg=[English]
        - title: Documentation for Active IQ Unified Manager 9.11
          url: https://docs.netapp.com/us-en/active-iq-unified-manager-911/
        - title: Documentation for earlier versions
          url: https://docs.netapp.com/ocum-99/topic/com.netapp.ndc.ocum-vers/GUID-DA5B426C-61E1-45E3-B2BE-834636433934.html
        - title: Documentation for the latest version of Active IQ Unified Manager
          url: https://docs.netapp.com/us-en/active-iq-unified-manager/index.html


