---
settings:
  name: Active IQ Unified Manager
  downlevel: true
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
  versions:
    - version-number: "9.7"
      url: /active-iq-unified-manager-97
    - version-number: "9.9"
      url: /active-iq-unified-manager-99
    - version-number: "9.8"
      url: /active-iq-unified-manager-98
sidebar:
  entries:
    - title: Active IQ Unified Manager 9.7 docs
      url: "/index.html"
    - title: Release notes
      url: "/release-notes.html"
    - title: Get started
      entries:
        - title: Quick start install for VMware vSphere
          url: /install-vapp/qsg-vapp.html
        - title: Quick start install for Linux
          url: /install-linux/qsg-linux.html
        - title: Quick start install for Windows
          url: /install-windows/qsg-windows.html
    - section: install-vapp
    - section: install-linux
    - section: install-windows
    - section: config
    - section: online-help
    - section: performance-checker
    - section: health-checker
    - section: data-protection
    - section: reporting
    - section: api-automation
    - title: Legal notices
      url: "/legal-notices.html"
      