---
permalink: install-vapp/task-upgrading-the-unified-manager-virtual-appliance-vapp.html
sidebar: sidebar
keywords: 
summary: 'You can upgrade from Unified Manager version 9.5 or 9.6 to 9.7.'
---
= Upgrading the Unified Manager virtual appliance
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade from Unified Manager version 9.5 or 9.6 to 9.7.

== Before you begin

* You must have downloaded the `.iso` file from the NetApp Support Site.
* The system on which you are upgrading Unified Manager must meet the system and software requirements.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Virtual infrastructure requirements]
+
xref:reference-vmware-software-and-installation-requirements.adoc[VMware software and installation requirements]

* For vSphere 6.5 and 6.7 users, you must have installed the VMware Remote Console (VMRC).
* During upgrade, you may be prompted to confirm on whether you want to keep the previous, default settings for retaining performance data for 13 months or to change it to 6 months. On confirming, the historical performance data is purged after 6 months.
* You must have the following information:
 ** Login credentials for the NetApp Support Site
 ** Credentials for accessing the VMware vCenter Server and vSphere Web Client (for vSphere version 6.5 or 6.7) or vSphere Client (for vSphere version 6.0)
 ** Credentials for the Unified Manager maintenance user

== About this task

During the upgrade process, Unified Manager is unavailable. You should complete any running operations before upgrading Unified Manager.

If you have paired Workflow Automation and Unified Manager, you must manually update the host name in Workflow Automation.

== Steps

. In the vSphere Client, click *Home* > *Inventory* > *VMs and Templates*.
. Select the virtual machine (VM) on which the Unified Manager virtual appliance is installed.
. If the Unified Manager VM is running, navigate to *Summary* > *Commands* > *Shut Down Guest*.
. Create a backup copy--such as a snapshot or clone--of the Unified Manager VM to create an application-consistent backup.
. From the vSphere Client, power on the Unified Manager VM.
. Select the Unified Manager upgrade image:
+
[cols="1a,1a" options="header"]
|===
| If you are using...| Then do this...
a|
vSphere 6.0
a|

 .. Click the *CD/DVD Drive* icon, and select *Connect to ISO image on local disk*.
 .. Select the `ActiveIQUnifiedManager-<version>-virtual-update.iso` file, and click *Open*.

a|
vSphere 6.5 or 6.7
a|

 .. Launch the VMware Remote Console.
 .. Click the *CDROM* icon, and select *Connect to Disk Image File (.iso)*.
 .. Select the `ActiveIQUnifiedManager-<version>-virtual-update.iso` file, and click *Open*.

+
|===

. Click the *Console* tab.
. Log in to the Unified Manager maintenance console.
. In the *Main Menu*, select *Upgrade*.
+
A message is displayed that Unified Manager is to be unavailable during the upgrade process, and is to resume after completion.

. Type `y` to continue.
+
A warning is displayed, reminding you to back up the virtual machine on which the virtual appliance resides.

. Type `y` to continue.
+
The upgrade process and the restart of Unified Manager services can take several minutes to complete.

. Press any key to continue.
+
You are automatically logged out of the maintenance console.

. Log in to the maintenance console, and verify the version of Unified Manager.

== After you finish

You can log in to the web UI to use the upgraded version of Unified Manager. Note that you must wait for the discovery process to finish before performing any task in the UI.
