---
permalink: install-windows/task_changing_the_jboss_password_on_windows.html
sidebar: sidebar
keywords: 
summary: 'You can create a new, custom JBoss password to overwrite the default password that is set during installation. This task is optional, but some sites might require this security capability to override the Unified Manager installation default setting. This operation also changes the password JBoss uses to access MySQL.'
---
= Changing the JBoss password
:icons: font
:imagesdir: ../media/

[.lead]
You can create a new, custom JBoss password to overwrite the default password that is set during installation. This task is optional, but some sites might require this security capability to override the Unified Manager installation default setting. This operation also changes the password JBoss uses to access MySQL.

== Before you begin

* You must have Windows admin privileges for the system on which Unified Manager is installed.
* You must have the password for the MySQL root user.
* You must be able to access the NetApp-provided `password.bat` script in the directory `\Program Files\NetApp\essentials\bin`.

== Steps

. Log in as the admin user on the Unified Manager host machine.
. Use the Windows Services console to stop the following Unified Manager services:
 ** NetApp Active IQ Acquisition Service (Ocie-au)
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
. Launch the `password.bat` script to begin the password change process: `C:\Program Files\NetApp\essentials\bin> password.bat resetJBossPassword`
. When prompted, enter the MySQL root user password.
. When prompted, enter the current JBoss user password.
+
The default password is `D11h1aMu@79%`.

. When prompted, enter the new JBoss user password, and then enter it again for confirmation.
+
Confirmation messages appear as the changes are made, and then you are prompted one last time for the new JBoss user password.

. Enter the new JBoss user password one more time.
. When the script completes, start the Unified Manager services by using the Windows Services console:
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
 ** NetApp Active IQ Acquisition Service (Ocie-au)
. After all of the services are started, you can log in to the Unified Manager UI.
