---
permalink: install-windows/task-upgrading-to-unified-manager-on-microsoft-windows.html
sidebar: sidebar
keywords: 
summary: 'You can upgrade Unified Manager 9.5 or 9.6 to 9.7 by downloading and running the installation file on the Windows platform.'
---
= Upgrading Unified Manager
:icons: font
:imagesdir: ../media/

[.lead]
You can upgrade Unified Manager 9.5 or 9.6 to 9.7 by downloading and running the installation file on the Windows platform.

== Before you begin

* The system on which you are upgrading Unified Manager must meet the system and software requirements.
+
xref:concept-virtual-infrastructure-or-hardware-system-requirements.adoc[Hardware system requirements]
+
xref:reference-windows-software-and-installation-requirements.adoc[Windows software and installation requirements]
+
[NOTE]
====
Starting with Unified Manager 9.5, OpenJDK is provided in the installation package and installed automatically. Oracle Java is not supported starting with Unified Manager 9.5.
====
+
[NOTE]
====
Starting with Unified Manager 9.4, Microsoft .NET 4.5.2 or greater is required. Make sure you have the correct version of .NET installed before starting the upgrade.
====

* You must have Windows administrator privileges. Ensure that your user name does not begin with an exclamation mark "`!`". Installation of Unified Manager might fail if the user name of user running the installation begins with "`!`".
* You must have valid credentials to log in to the NetApp Support Site.
* To avoid data loss, you must have created a backup of the Unified Manager machine in case there is an issue during the upgrade.
* You must have adequate disk space available to perform the upgrade.
+
The available space on the installation drive must be 2.5 GB larger than the size of the data directory. The upgrade stops and displays an error message indicating the amount of space to be added if there is not enough free space.

* During upgrade, you may be prompted to confirm whether you want to keep the previous, default settings for retaining performance data for 13 months or to change it to 6 months. On confirming, the historical performance data after 6 months is purged.
* Before upgrading, you must close any open files or folder in `<InstallDir\>\JDK` and `MySQL Data Directory`.

== About this task

During the upgrade process, Unified Manager is unavailable. You should complete any running operations before upgrading Unified Manager.

If Unified Manager is paired with an instance of OnCommand Workflow Automation, and there are new versions of software available for both products, you must disconnect the two products and then set up a new Workflow Automation connection after performing the upgrades. If you are performing an upgrade to only one of the products, then you should log into Workflow Automation after the upgrade and verify that it is still acquiring data from Unified Manager.

== Steps

. Log in to the NetApp Support Site, and locate the *Download* page for installing Unified Manager on the Windows platform.
+
https://mysupport.netapp.com/products/index.html

. Download the Unified Manager Windows installation file to a target directory in the Windows system.
. Right-click and run the Unified Manager installer executable `(.exe)` file as an administrator.
+
Unified Manager prompts you with the following message:
+
----
This setup will perform an upgrade of Unified Manager. Do you want to continue?
----

. Click *Yes*, and then click *Next*.
. Enter the MySQL8 root password that was set during installation, and then click *Next*.
. Log in to the Unified Manager web UI, and verify the version number.

== After you finish

[NOTE]
====
To perform a silent upgrade of Unified Manager, run the following command: `ActiveIQUnifiedManager-<version\>.exe /s /v"MYSQL_PASSWORD=netapp21! /qn /l*v C:\install.log`
====
