---
permalink: install-windows/task_upgrading_mysql_on_windows_ocum.html
sidebar: sidebar
keywords: Active IQ Unified Manager
summary: 'On the Windows server on which Unified Manager is installed, you can upgrade MySQL to a higher version to obtain fixes for security vulnerabilities. For any minor upgrade, the base version of MySQL must be 8.0.17 or later. If the installed version of MySQL on your system is earlier than 8.0.17, the Unified Manager 9.7 upgrade process automatically upgrades MySQL to 8.0.17. You must not run a standalone upgrade of MySQL from an earlier version to 8.0.17.'
---
= Upgrading MySQL
:icons: font
:imagesdir: ../media/

[.lead]
On the Windows server on which Unified Manager is installed, you can upgrade MySQL to a higher version to obtain fixes for security vulnerabilities. For any minor upgrade, the base version of MySQL must be 8.0.17 or later. If the installed version of MySQL on your system is earlier than 8.0.17, the Unified Manager 9.7 upgrade process automatically upgrades MySQL to 8.0.17. You must not run a standalone upgrade of MySQL from an earlier version to 8.0.17.

== Before you begin

[NOTE]
====
If the installed version of MySQL on your system is 5.7, then you must not attempt to directly upgrade MySQL to version 8.0.17. It results in application data loss.
====

* You must have Windows admin privileges for the system on which Unified Manager is installed.
* You must have the password for the MySQL root user.

== Steps

. Log in as the admin user on the Unified Manager host machine.
. Download the appropriate version of MySQL to the target system.
. Use the Windows Services console to stop the following Unified Manager services:
 ** NetApp Active IQ Acquisition Service (Ocie-au)
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
 ** MYSQL8
. Click the `.msi` package to invoke the upgrade of MySQL and follow the instructions on the screen to complete the upgrade.
. Start the Unified Manager services by using the Windows Services console:
 ** MYSQL8
 ** NetApp Active IQ Management Server Service (Oncommandsvc)
 ** NetApp Active IQ Acquisition Service (Ocie-au)
